package com.example.ui.utils

object LanguageUtils {
    private val translations = mapOf(
        "en" to mapOf(
            "app_tagline" to "Cinematic Studio AI",
            "email" to "Email Address",
            "displayName" to "Creator Name",
            "password" to "Security Phrase / Password",
            "login" to "Enter Studio",
            "register" to "Create Account",
            "signup_prompt" to "Begin your journey? Sign up",
            "signin_prompt" to "Already a catalogued creator? Sign in",
            "prompt_placeholder" to "A majestic glowing dragon breathing cybernetic neon fire, cinematic camera pan...",
            "negative_prompt" to "Negative Prompt (exclusions: blur, handshake, static, bad light)",
            "aspect_ratio" to "Aspect Ratio",
            "resolution_label" to "Resolution Settings",
            "generate_btn" to "IGNITE MODEL ENGINE",
            "credits_remaining" to "Credits Remaining",
            "history" to "Creations Grid",
            "profile" to "Creator Profile",
            "settings" to "Settings Console",
            "admin_panel" to "Internal Core Admin",
            "download" to "Download MP4",
            "share" to "Share Broadcast",
            "enhance_btn" to "Enhance Prompt",
            "mock_render_label" to "Prompt Pipeline Latency (seconds)",
            "logout" to "Terminate Session",
            "welcome" to "Welcome to Dragon AI",
            "empty_history" to "Your creation pool is empty. Prompt the core to ignite the engine!",
            "admin_stats" to "Engine Framework Diagnostics",
            "theme_mode" to "Dark Dimension Motif",
            "lang_select" to "Synthesizer Language",
            "render_warning" to "Security Notice: API key exposed via BuildConfig. Protect your local build.",
            "duration_label" to "Video Duration",
            "duration_sub" to "Specify the length of your cinematic render selection (seconds)",
            "bookmarks_label" to "Bookmarks",
            "transition_label" to "Transition Effect",
            "transition_sub" to "Select cinematic motion blend between keyframes",
            "quick_preview_label" to "Quick Preview",
            "quick_preview_sub" to "Generate a low-resolution static draft frame before rendering the full video",
            "quick_preview_btn" to "Quick Preview Frame",
            "quick_preview_status" to "Synthesizing Draft Frame...",
            "use_preview_as_keyframe" to "Proceed with HD Video Gen"
        ),
        "es" to mapOf(
            "app_tagline" to "AI de Estudio Cinemático",
            "email" to "Dirección de Correo",
            "displayName" to "Nombre de Creador",
            "password" to "Frase de Seguridad / Contraseña",
            "login" to "Entrar al Estudio",
            "register" to "Registrarse",
            "signup_prompt" to "¿Iniciar viaje? Registrarse",
            "signin_prompt" to "¿Ya tienes una cuenta? Iniciar sesión",
            "prompt_placeholder" to "Un majestuoso dragón brillante respirando fuego de neón, paneo cinemático...",
            "negative_prompt" to "Prompt Negativo (evitar: borroso, tembloroso, mala luz)",
            "aspect_ratio" to "Relación de Aspecto",
            "resolution_label" to "Resolución",
            "generate_btn" to "ENCENDER MOTOR DE IA",
            "credits_remaining" to "Créditos Restantes",
            "history" to "Ver Creaciones",
            "profile" to "Perfil de Creador",
            "settings" to "Consola de Ajustes",
            "admin_panel" to "Panel de Admin Interno",
            "download" to "Descargar MP4",
            "share" to "Compartir Video",
            "enhance_btn" to "Mejorar Prompt",
            "mock_render_label" to "Latencia del Pipeline (segundos)",
            "logout" to "Cerrar Sesión",
            "welcome" to "Bienvenido a Dragon AI",
            "empty_history" to "Tu historial está vacío. ¡Enciende el generador!",
            "admin_stats" to "Diagnósticos del Framework",
            "theme_mode" to "Tema de Modo Oscuro",
            "lang_select" to "Idioma del Sintetizador",
            "render_warning" to "Aviso: Clave de API expuesta en BuildConfig.",
            "duration_label" to "Duración del Video",
            "duration_sub" to "Especifica la duración de tu render cinemático en segundos",
            "bookmarks_label" to "Marcadores",
            "transition_label" to "Efecto de Transición",
            "transition_sub" to "Selecciona la mezcla de movimiento cinemático entre fotogramas",
            "quick_preview_label" to "Vista Previa Rápida",
            "quick_preview_sub" to "Genera un fotograma de borrador estático de baja resolución antes de renderizar el video completo",
            "quick_preview_btn" to "Fotograma de Vista Previa",
            "quick_preview_status" to "Sintetizando Fotograma de Borrador...",
            "use_preview_as_keyframe" to "Proceder con la Generación"
        ),
        "hi" to mapOf(
            "app_tagline" to "सिनेमैटिक स्टूडियो एआई",
            "email" to "ईमेल पता",
            "displayName" to "निर्माता का नाम",
            "password" to "सुरक्षा कोड / पासवर्ड",
            "login" to "स्टूडियो में प्रवेश करें",
            "register" to "खाता बनाएं",
            "signup_prompt" to "यात्रा शुरू करें? पंजीकरण करें",
            "signin_prompt" to "पहले से ही खाता है? लॉगिन करें",
            "prompt_placeholder" to "एक राजसी विशाल अजगर जो साइबरनेटीक नियॉन आग उगल रहा है, सिनेमैटिक शॉट...",
            "negative_prompt" to "नकारात्मक संकेत (वर्जित: धुंधला, हिलना, ख़राब रोशनी)",
            "aspect_ratio" to "पहलू अनुपात",
            "resolution_label" to "रिज़ॉल्यूशन सेटिंग्स",
            "generate_btn" to "मॉडल इंजन प्रज्वलित करें",
            "credits_remaining" to "बचे हुए क्रेडिट",
            "history" to "मेरी कृतियां",
            "profile" to "प्रोफाइल",
            "settings" to "कंसोल सेटिंग्स",
            "admin_panel" to "आंतरिक एडमिन",
            "download" to "एमपी4 डाउनलोड",
            "share" to "साझा करें",
            "enhance_btn" to "प्रॉम्प्ट सुधारें",
            "mock_render_label" to "पाइपलाइन विलंबता (सेकंड)",
            "logout" to "लॉगआउट",
            "welcome" to "ड्रैगन एआई में आपका स्वागत है",
            "empty_history" to "अभी तक कोई वीडियो नहीं है, पहला वीडियो बनाएं!",
            "admin_stats" to "सिस्टम निदान",
            "theme_mode" to "डार्क मोड थीम",
            "lang_select" to "भाषा का चयन",
            "render_warning" to "नोटिस: एपीआई कुंजी स्थानिक निर्माण में खुली है।",
            "duration_label" to "वीडियो अवधि",
            "duration_sub" to "अपने सिनेमाई रेंडर चयन की लंबाई सेकंड में निर्दिष्ट करें",
            "bookmarks_label" to "बुकमार्क",
            "transition_label" to "ट्रांज़िशन प्रभाव",
            "transition_sub" to "कीफ्रेม के बीच सिनेमाई गति मिश्रण का चयन करें",
            "quick_preview_label" to "त्वरित पूर्वावलोकन",
            "quick_preview_sub" to "पूर्ण वीडियो प्रस्तुत करने से पहले कम-रिज़ॉल्यूशन वाला स्थैतिक ड्राफ्ट फ़्रेम उत्पन्न करें",
            "quick_preview_btn" to "त्वरित पूर्वावलोकन फ़्रेम",
            "quick_preview_status" to "प्रारूप फ़्रेम का संश्लेषण...",
            "use_preview_as_keyframe" to "एचडी वीडियो जनरेशन के साथ आगे बढ़ें"
        ),
        "zh" to mapOf(
            "app_tagline" to "电影级AI视频创作室",
            "email" to "电子邮箱地址",
            "displayName" to "创作者姓名",
            "password" to "密码",
            "login" to "进入工作室",
            "register" to "创建新账户",
            "signup_prompt" to "开始您的创作？注册",
            "signin_prompt" to "已有账户？登录",
            "prompt_placeholder" to "一条吐着霓虹极光烈焰的机甲神龙，电影级横移镜头...",
            "negative_prompt" to "反向提示词 (排除: 模糊, 抖动, 穿模)",
            "aspect_ratio" to "画面比例",
            "resolution_label" to "分辨率设置",
            "generate_btn" to "点燃AI视频引擎",
            "credits_remaining" to "剩余点数",
            "history" to "创作历史",
            "profile" to "个人档案",
            "settings" to "设置控制面板",
            "admin_panel" to "系统内部管理",
            "download" to "下载 MP4",
            "share" to "分享作品",
            "enhance_btn" to "AI 强化提示词",
            "mock_render_label" to "渲染推演所需时长 (秒)",
            "logout" to "安全退出",
            "welcome" to "欢迎来到 傲龙 视频大模型平台",
            "empty_history" to "历史库空空如也，快开启你的奇妙灵感吧！",
            "admin_stats" to "引擎运行参数监控",
            "theme_mode" to "深色空间视效",
            "lang_select" to "系统操作语言",
            "render_warning" to "安全提示: API 密钥已嵌入，请注意本地安全防护。",
            "duration_label" to "视频时长",
            "duration_sub" to "指定您的电影级视频渲染长度 (秒)",
            "bookmarks_label" to "书签收藏",
            "transition_label" to "过渡效果",
            "transition_sub" to "选择关键帧之间的电影级运动混合方式",
            "quick_preview_label" to "快速预览",
            "quick_preview_sub" to "在渲染完整的高清视频之前，生成一个低分辨率的静态草图帧",
            "quick_preview_btn" to "生成预览帧",
            "quick_preview_status" to "正在合成低清草图帧...",
            "use_preview_as_keyframe" to "以此预览渲染高清视频"
        ),
        "fr" to mapOf(
            "app_tagline" to "Studio Cinématique IA",
            "email" to "Adresse E-mail",
            "displayName" to "Nom du Créateur",
            "password" to "Code de Sécurité / Mot de Passe",
            "login" to "Entrer au Studio",
            "register" to "Créer un Compte",
            "signup_prompt" to "Démarrer l'aventure ? S'inscrire",
            "signin_prompt" to "Déjà créateur ? Se connecter",
            "prompt_placeholder" to "Un dragon majestueux crachant du feu de néon, panoramique fluide...",
            "negative_prompt" to "Prompt Négatif (exclure: flou, tremblement, bruit)",
            "aspect_ratio" to "Format d'Image",
            "resolution_label" to "Paramètres Résolution",
            "generate_btn" to "DÉMARRER LE MOTEUR",
            "credits_remaining" to "Crédits Restants",
            "history" to "Bibliothèque",
            "profile" to "Profil Créateur",
            "settings" to "Tableau de Réglages",
            "admin_panel" to "Console Administrative",
            "download" to "Télécharger MP4",
            "share" to "Partager la Vidéo",
            "enhance_btn" to "Améliorer le Prompt",
            "mock_render_label" to "Latence de Rendu (secondes)",
            "logout" to "Déconnecter",
            "welcome" to "Bienvenue sur Dragon AI",
            "empty_history" to "Votre historique est vide. Donnez vie à vos idées !",
            "admin_stats" to "Diagnostics du Système",
            "theme_mode" to "Thème Ombre Sombre",
            "lang_select" to "Langue Locale",
            "render_warning" to "Alerte: Clé d'API ouverte dans BuildConfig.",
            "duration_label" to "Durée de la Vidéo",
            "duration_sub" to "Spécifiez la longueur de rendu cinématographique en secondes",
            "bookmarks_label" to "Favoris",
            "transition_label" to "Effet de Transition",
            "transition_sub" to "Sélectionnez le mélange de mouvement cinématographique entre les images clés",
            "quick_preview_label" to "Aperçu Rapide",
            "quick_preview_sub" to "Générez une image de brouillon statique basse résolution avant de lancer le rendu vidéo HD",
            "quick_preview_btn" to "Cadre d'Aperçu Rapide",
            "quick_preview_status" to "Synthèse du cadre brouillon...",
            "use_preview_as_keyframe" to "Procéder au rendu vidéo HD"
        )
    )

    fun translate(key: String, langCode: String): String {
        val selectedLang = translations[langCode] ?: translations["en"]!!
        return selectedLang[key] ?: translations["en"]!![key] ?: key
    }
}
